import { auth,db } from "./firebase-refleksjon.js";import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.6.0/firebase-auth.js";import { collection,getDocs,doc,getDoc,updateDoc,addDoc,serverTimestamp,query,where } from "https://www.gstatic.com/firebasejs/12.6.0/firebase-firestore.js";
const $=id=>document.getElementById(id);let players=[],accounts=[],requests=[],allRequests=[],messages=[];
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function load(){try{const ps=await getDocs(collection(db,"spillere"));players=ps.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(a.navn||a.name||"").localeCompare(String(b.navn||b.name||""),"no"));const as=await getDocs(collection(db,"playerAccounts"));accounts=as.docs.map(d=>({uid:d.id,...d.data()}));try{const rs=await getDocs(collection(db,"developmentRequests"));allRequests=rs.docs.map(d=>({id:d.id,...d.data()}));requests=allRequests.filter(r=>r.status==="open")}catch(err){console.error("developmentRequests:",err);requests=[];allRequests=[]}try{const ms=await getDocs(collection(db,"developmentMessages"));messages=ms.docs.map(d=>({id:d.id,...d.data()}))}catch(err){console.error("developmentMessages:",err);messages=[]}render()}catch(err){console.error("Spillerbrukere load:",err);$("pendingList").innerHTML="<p class=\"empty\">Kunne ikke laste spillerkontoer: "+esc(err.code||err.message)+"</p>";$("approvedList").innerHTML="<p class=\"empty\">Se feilmeldingen over.</p>";$("requestList").innerHTML="<p class=\"empty\">Se feilmeldingen over.</p>"}}
function playerName(id){const p=players.find(x=>x.id===id);return p?.navn||p?.name||id||"Ukjent spiller"}function opts(){return '<option value="">Velg spiller…</option>'+players.map(p=>'<option value="'+esc(p.id)+'">'+esc(p.navn||p.name||p.id)+'</option>').join("")}
function render(){$("pendingCount").textContent=accounts.filter(a=>!a.approved).length;$("approvedCount").textContent=accounts.filter(a=>a.approved).length;$("requestCount").textContent=requests.length;
const pending=accounts.filter(a=>!a.approved);$("pendingList").innerHTML=pending.length?pending.map(a=>'<article class="userCard"><div class="userTop"><div><h3>'+esc(a.name||"Uten navn")+'</h3><p>'+esc(a.email||"")+'</p></div><span class="badge">VENTER</span></div><div class="controls"><select id="sel-'+a.uid+'">'+opts()+'</select><button class="approve" data-uid="'+a.uid+'">Godkjenn</button></div></article>').join(""):'<p class="empty">Ingen venter på godkjenning.</p>';
const approved=accounts.filter(a=>a.approved);$("approvedList").innerHTML=approved.length?approved.map(a=>'<article class="userCard"><div class="userTop"><div><h3>'+esc(a.name)+'</h3><p>'+esc(a.email)+'</p><p class="meta">Koblet til: <strong>'+esc(playerName(a.playerId))+'</strong></p></div><span class="badge ok">GODKJENT</span></div><div class="controls"><button class="communication" data-communication="'+a.uid+'">Kommunikasjon</button><button class="resetApproval danger" data-reset="'+a.uid+'">Fjern godkjenning (test)</button></div></article>').join(""):'<p class="empty">Ingen godkjente spillerkontoer ennå.</p>';
$("requestList").innerHTML=requests.length?requests.map(r=>{const a=accounts.find(x=>x.uid===r.uid),thread=messages.filter(m=>m.requestId===r.id).sort((x,y)=>ts(x.createdAt)-ts(y.createdAt));const threadHtml='<div class="activeThread"><div class="threadItem player"><div class="threadMeta"><strong>'+esc(a?.name||playerName(r.playerId))+'</strong><span>Forespørsel · '+esc(dateText(r.createdAt))+'</span></div><p>'+esc(r.message||"Ønsker generell tilbakemelding")+'</p></div>'+thread.map(m=>{const parent=m.replyToMessageId?messages.find(x=>x.id===m.replyToMessageId):null;return '<div class="threadItem '+(m.senderRole==="coach"?"coach":"player")+'">'+(parent?'<div class="threadReplyRef"><span>Svar på</span>'+esc(parent.text||"")+'</div>':'')+'<div class="threadMeta"><strong>'+esc(m.senderRole==="coach"?"Trener":(a?.name||playerName(r.playerId)))+'</strong><span>'+esc(dateText(m.createdAt))+'</span></div><p>'+esc(m.text||"")+'</p></div>'}).join("")+'</div>';return '<article class="userCard"><div class="userTop"><div><h3>'+esc(a?.name||playerName(r.playerId))+'</h3><p>Aktiv utviklingssamtale</p></div><span class="badge">AKTIV</span></div>'+threadHtml+'<div class="reply"><textarea id="reply-'+r.id+'" placeholder="Skriv svar til spilleren…"></textarea><div class="replyActions"><button class="send" data-request="'+r.id+'">Send svar</button><button class="resolve" data-resolve="'+r.id+'">Ferdig</button></div></div></article>'}).join(""):'<p class="empty">Ingen aktive forespørsler.</p>';
document.querySelectorAll(".approve").forEach(b=>b.onclick=approve);document.querySelectorAll(".send").forEach(b=>b.onclick=sendReply);document.querySelectorAll(".resolve").forEach(b=>b.onclick=resolve);document.querySelectorAll(".resetApproval").forEach(b=>b.onclick=resetApproval);document.querySelectorAll(".communication").forEach(b=>b.onclick=openCommunication)}
function ts(v){if(!v)return 0;if(typeof v.toDate==="function")return v.toDate().getTime();if(v.seconds)return v.seconds*1000;return 0}
function dateText(v){const n=ts(v);return n?new Date(n).toLocaleString("no-NO",{dateStyle:"medium",timeStyle:"short"}):"Dato ikke tilgjengelig"}
function openCommunication(e){const uid=e.currentTarget.dataset.communication,acc=accounts.find(a=>a.uid===uid);if(!acc)return;const reqs=allRequests.filter(r=>r.uid===uid||r.playerId===acc.playerId);const reqIds=new Set(reqs.map(r=>r.id));const msgs=messages.filter(m=>m.uid===uid||m.playerId===acc.playerId||reqIds.has(m.requestId));const rows=[...reqs.map(r=>({time:r.createdAt,who:acc.name||playerName(acc.playerId),kind:"Forespørsel",text:r.message||"Ønsker generell tilbakemelding"})),...msgs.map(m=>({time:m.createdAt,who:m.senderRole==="coach"?"Trener":(acc.name||playerName(acc.playerId)),kind:m.senderRole==="coach"?"Tilbakemelding":"Svar fra spiller",text:m.text||""}))].sort((a,b)=>ts(a.time)-ts(b.time));const content=rows.length?rows.map(x=>'<article class="exportMessage"><div class="exportMeta"><strong>'+esc(x.who)+'</strong><span>'+esc(x.kind)+' · '+esc(dateText(x.time))+'</span></div><p>'+esc(x.text).replace(/\n/g,"<br>")+'</p></article>').join(""):'<p class="empty">Ingen kommunikasjon er registrert for denne spilleren.</p>';$("communicationTitle").textContent="Kommunikasjon · "+(acc.name||playerName(acc.playerId));$("communicationSub").textContent="All registrert utviklingskommunikasjon mellom trener og spiller.";$("communicationBody").innerHTML=content;$("communicationModal").hidden=false;document.body.classList.add("modalOpen")}
function closeCommunication(){$("communicationModal").hidden=true;document.body.classList.remove("modalOpen")}
$("closeCommunication").onclick=closeCommunication;$("closeCommunicationBottom").onclick=closeCommunication;$("communicationModal").onclick=e=>{if(e.target===$("communicationModal"))closeCommunication()};$("printCommunication").onclick=()=>window.print();
async function approve(e){const uid=e.currentTarget.dataset.uid,sel=$("sel-"+uid),playerId=sel.value;if(!playerId)return alert("Velg riktig spiller først.");const acc=accounts.find(a=>a.uid===uid),taken=accounts.find(a=>a.approved&&a.playerId===playerId);if(taken)return alert("Denne spilleren er allerede koblet til "+taken.name+".");if(!confirm("Koble "+acc.name+" ("+acc.email+") til "+playerName(playerId)+"?"))return;await updateDoc(doc(db,"playerAccounts",uid),{approved:true,playerId,approvedAt:serverTimestamp(),approvedBy:auth.currentUser.uid});await load()}
async function resetApproval(e){const uid=e.currentTarget.dataset.reset,acc=accounts.find(a=>a.uid===uid);if(!acc)return;if(!confirm("Fjerne godkjenningen for "+acc.name+"? Kontoen beholdes, men må godkjennes på nytt."))return;await updateDoc(doc(db,"playerAccounts",uid),{approved:false,playerId:null});await load()}
async function sendReply(e){const btn=e.currentTarget,r=requests.find(x=>x.id===btn.dataset.request);if(!r)return;const ta=$("reply-"+r.id),text=ta.value.trim();if(!text)return alert("Skriv en tilbakemelding først.");btn.disabled=true;btn.textContent="Sender…";try{await addDoc(collection(db,"developmentMessages"),{playerId:r.playerId,uid:r.uid,text,senderRole:"coach",createdAt:serverTimestamp(),requestId:r.id});await load()}catch(err){console.error("sendReply:",err);alert("Kunne ikke sende tilbakemeldingen. Prøv igjen.");btn.disabled=false;btn.textContent="Send svar"}}
async function resolve(e){const id=e.currentTarget.dataset.resolve;if(!confirm("Markere denne forespørselen som ferdig?"))return;await updateDoc(doc(db,"developmentRequests",id),{status:"resolved",resolvedAt:serverTimestamp(),resolvedBy:auth.currentUser.uid});await load()}
onAuthStateChanged(auth,async user=>{try{if(!user)return location.href="index.html";const s=await getDoc(doc(db,"users",user.uid));if(!s.exists()||s.data().role!=="coach")return location.href="index.html";await load()}catch(err){console.error("Auth/admin:",err);$("pendingList").innerHTML="<p class=\"empty\">Feil: "+esc(err.code||err.message)+"</p>"}});