import { auth,db,guardianFunctions } from "./firebase-refleksjon.js";import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.6.0/firebase-auth.js";import { httpsCallable } from "https://www.gstatic.com/firebasejs/12.6.0/firebase-functions.js";import { collection,getDocs,doc,getDoc,updateDoc,addDoc,serverTimestamp,query,where,onSnapshot,writeBatch } from "https://www.gstatic.com/firebasejs/12.6.0/firebase-firestore.js";
const $=id=>document.getElementById(id);let players=[],accounts=[],guardianAccounts=[],guardianRequests=[],requests=[],allRequests=[],messages=[],unsubAccounts=null,unsubGuardians=null,unsubGuardianRequests=null,unsubRequests=null,unsubMessages=null,realtimeStarted=false;
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function load(){try{const ps=await getDocs(collection(db,"spillere"));players=ps.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(a.navn||a.name||"").localeCompare(String(b.navn||b.name||""),"no"));const as=await getDocs(collection(db,"playerAccounts"));accounts=as.docs.map(d=>({uid:d.id,...d.data()}));const gs=await getDocs(collection(db,"guardianAccounts"));guardianAccounts=gs.docs.map(d=>({uid:d.id,...d.data()}));const grs=await getDocs(collection(db,"guardianRequests"));guardianRequests=grs.docs.map(d=>({id:d.id,...d.data()}));try{const rs=await getDocs(collection(db,"developmentRequests"));allRequests=rs.docs.map(d=>({id:d.id,...d.data()}));requests=allRequests.filter(r=>r.status==="open")}catch(err){console.error("developmentRequests:",err);requests=[];allRequests=[]}try{const ms=await getDocs(collection(db,"developmentMessages"));messages=ms.docs.map(d=>({id:d.id,...d.data()}))}catch(err){console.error("developmentMessages:",err);messages=[]}render()}catch(err){console.error("Spillerbrukere load:",err);$("pendingList").innerHTML="<p class=\"empty\">Kunne ikke laste spillerkontoer: "+esc(err.code||err.message)+"</p>";$("approvedList").innerHTML="<p class=\"empty\">Se feilmeldingen over.</p>";$("requestList").innerHTML="<p class=\"empty\">Se feilmeldingen over.</p>"}}
function startRealtime(){if(realtimeStarted)return;realtimeStarted=true;unsubAccounts=onSnapshot(collection(db,"playerAccounts"),snap=>{accounts=snap.docs.map(d=>({uid:d.id,...d.data()}));render()},err=>console.error("playerAccounts live:",err));unsubGuardians=onSnapshot(collection(db,"guardianAccounts"),snap=>{guardianAccounts=snap.docs.map(d=>({uid:d.id,...d.data()}));render()},err=>console.error("guardianAccounts live:",err));unsubGuardianRequests=onSnapshot(collection(db,"guardianRequests"),snap=>{guardianRequests=snap.docs.map(d=>({id:d.id,...d.data()}));render()},err=>console.error("guardianRequests live:",err));unsubRequests=onSnapshot(collection(db,"developmentRequests"),snap=>{allRequests=snap.docs.map(d=>({id:d.id,...d.data()}));requests=allRequests.filter(r=>r.status==="open");render()},err=>console.error("developmentRequests live:",err));unsubMessages=onSnapshot(collection(db,"developmentMessages"),snap=>{messages=snap.docs.map(d=>({id:d.id,...d.data()}));render()},err=>console.error("developmentMessages live:",err))}
function playerName(id){const p=players.find(x=>x.id===id);return p?.navn||p?.name||id||"Ukjent spiller"}function opts(){return '<option value="">Velg spiller…</option>'+players.map(p=>'<option value="'+esc(p.id)+'">'+esc(p.navn||p.name||p.id)+'</option>').join("")}
function renderGuardianRequests(){const root=$("guardianRequestList");if(!root)return;const pending=guardianRequests.filter(r=>r.status==="pending");root.innerHTML=pending.length?pending.map(r=>'<article class="userCard guardianRequestAdmin"><div class="accountTypeTag guardianType">FORESATT FRA SPILLER</div><div class="userTop"><div><h3>'+esc(r.guardianName||"Uten navn")+'</h3><p>'+esc(r.guardianEmail||"")+'</p><p class="meta"><strong>'+esc(r.playerName||playerName(r.playerId))+'</strong> har selv lagt til denne foresatte.</p></div><span class="badge">VENTER</span></div><div class="guardianApprovalNote">Godkjenn bare hvis dette ser riktig ut. Invitasjonen blir låst til e-postadressen over.</div><div class="controls guardianRequestControls"><button class="approveGuardianRequest" data-request="'+r.id+'">Godkjenn og klargjør invitasjon</button><button class="rejectGuardianRequest danger" data-request="'+r.id+'">Avvis</button></div></article>').join(""):'<p class="empty">Ingen forespørsler fra spillere venter.</p>';document.querySelectorAll(".approveGuardianRequest").forEach(b=>b.onclick=approveGuardianRequest);document.querySelectorAll(".rejectGuardianRequest").forEach(b=>b.onclick=rejectGuardianRequest)}
async function approveGuardianRequest(e){const id=e.currentTarget.dataset.request,r=guardianRequests.find(x=>x.id===id);if(!r)return;if(!confirm("Godkjenne "+r.guardianName+" som foresatt til "+(r.playerName||playerName(r.playerId))+"?\n\nInvitasjonen låses til "+r.guardianEmail+"."))return;const btn=e.currentTarget;btn.disabled=true;btn.textContent="Klargjør…";try{const fn=httpsCallable(guardianFunctions,"approveGuardianInvite");const result=await fn({requestId:id});const url=result.data.inviteUrl,email=result.data.email;if(result.data.emailSent){alert("Godkjent. Invitasjonen er sendt på e-post til "+email+".")}else{await navigator.clipboard.writeText(url).catch(()=>{});alert("Godkjent. Invitasjonslenken er kopiert.")}}catch(err){console.error(err);alert(err?.message||"Kunne ikke godkjenne forespørselen.")}finally{btn.disabled=false;btn.textContent="Godkjenn og klargjør invitasjon"}}
async function rejectGuardianRequest(e){const id=e.currentTarget.dataset.request,r=guardianRequests.find(x=>x.id===id);if(!r||!confirm("Avvise forespørselen om "+r.guardianName+"?"))return;await updateDoc(doc(db,"guardianRequests",id),{status:"rejected",rejectedAt:serverTimestamp(),rejectedBy:auth.currentUser.uid})}
function renderGuardians(){const root=$("guardianList");if(!root)return;const sorted=[...guardianAccounts].sort((a,b)=>String(a.name||"").localeCompare(String(b.name||""),"no"));root.innerHTML=sorted.length?'<div class="guardianCompactList">'+sorted.map(g=>{const linked=(g.playerIds||[]);return '<details class="guardianCompact"><summary><div class="guardianSummaryMain"><strong>'+esc(g.name||"Uten navn")+'</strong><span>'+esc(g.email||"")+'</span></div><div class="guardianSummaryLink">'+(linked.length?esc(linked.map(playerName).join(", ")):"Ingen spiller")+'</div><span class="badge '+(g.approved?"ok":"")+'">'+(g.approved?"AKTIV":"VENTER")+'</span><span class="guardianChevron">⌄</span></summary><div class="guardianDetails"><p class="meta">'+(linked.length?'Koblet til: <strong>'+esc(linked.map(playerName).join(", "))+'</strong>':'Ikke koblet til spiller ennå')+'</p><div class="controls guardianControls"><select id="guardian-sel-'+g.uid+'">'+opts()+'</select><button class="approveGuardian" data-guardian="'+g.uid+'">'+(g.approved?"Legg til spiller":"Godkjenn og koble")+'</button>'+(linked.length?'<button class="removeGuardianLink danger" data-guardian="'+g.uid+'">Administrer koblinger</button>':'')+'</div></div></details>'}).join("")+'</div>':'<p class="empty">Ingen foresattkontoer ennå.</p>';document.querySelectorAll(".approveGuardian").forEach(b=>b.onclick=approveGuardian);document.querySelectorAll(".removeGuardianLink").forEach(b=>b.onclick=manageGuardianLinks)}
async function approveGuardian(e){const uid=e.currentTarget.dataset.guardian,g=guardianAccounts.find(x=>x.uid===uid),playerId=$("guardian-sel-"+uid)?.value;if(!g||!playerId)return alert("Velg riktig spiller først.");const ids=[...(g.playerIds||[])];if(ids.includes(playerId))return alert("Foresatte er allerede koblet til "+playerName(playerId)+".");if(!confirm("Gi "+g.name+" lesetilgang til utviklingssamtalene til "+playerName(playerId)+"?"))return;ids.push(playerId);await updateDoc(doc(db,"guardianAccounts",uid),{approved:true,playerIds:ids,approvedAt:serverTimestamp(),approvedBy:auth.currentUser.uid})}
async function manageGuardianLinks(e){const uid=e.currentTarget.dataset.guardian,g=guardianAccounts.find(x=>x.uid===uid);if(!g)return;const ids=[...(g.playerIds||[])];if(!ids.length)return;const choices=ids.map((id,i)=>(i+1)+": "+playerName(id)).join("\n"),answer=prompt("Skriv nummeret på koblingen som skal fjernes:\n\n"+choices);if(!answer)return;const ix=Number(answer)-1;if(ix<0||ix>=ids.length)return alert("Ugyldig valg.");const removed=ids[ix];if(!confirm("Fjerne "+g.name+" sin tilgang til "+playerName(removed)+"?"))return;ids.splice(ix,1);await updateDoc(doc(db,"guardianAccounts",uid),{playerIds:ids,approved:ids.length>0})}

function render(){
const pending=accounts.filter(a=>!a.approved&&!a.rejected);
$("pendingCount").textContent=pending.length;
$("approvedCount").textContent=accounts.filter(a=>a.approved).length;
$("requestCount").textContent=requests.length;
$("pendingList").innerHTML=pending.length?pending.map(a=>'<article class="userCard"><div class="accountTypeTag playerType">⚽ SPILLERKONTO</div><div class="userTop"><div><h3>'+esc(a.name||"Uten navn")+'</h3><p>'+esc(a.email||"")+'</p></div><span class="badge">VENTER</span></div><p class="accountHelp">Denne kontoen skal kobles til spillerens egen spillerprofil.</p><div class="controls pendingControls"><select id="sel-'+a.uid+'">'+opts()+'</select><button class="approve" data-uid="'+a.uid+'">Godkjenn</button><button class="rejectAccount" data-reject="'+a.uid+'">Avvis registrering</button></div></article>').join(""):'<p class="empty">Ingen spillerkontoer venter på godkjenning.</p>';
renderPlayerHub();
document.querySelectorAll(".approve").forEach(b=>b.onclick=approve);
document.querySelectorAll(".rejectAccount").forEach(b=>b.onclick=rejectAccount);
document.querySelectorAll(".send").forEach(b=>b.onclick=sendReply);
document.querySelectorAll(".resolve").forEach(b=>b.onclick=resolve);
document.querySelectorAll(".resetApproval").forEach(b=>b.onclick=resetApproval);
document.querySelectorAll(".communication").forEach(b=>b.onclick=openCommunication);
document.querySelectorAll(".archiveOnly").forEach(b=>b.onclick=openArchive);
document.querySelectorAll(".coachReplyTo").forEach(b=>b.onclick=selectCoachReply);
document.querySelectorAll(".clearCoachReply").forEach(b=>b.onclick=clearCoachReply);
document.querySelectorAll(".editConversationTitle").forEach(b=>b.onclick=editConversationTitle);
document.querySelectorAll(".approveGuardianRequest").forEach(b=>b.onclick=approveGuardianRequest);
document.querySelectorAll(".rejectGuardianRequest").forEach(b=>b.onclick=rejectGuardianRequest);
document.querySelectorAll(".removeGuardianLink").forEach(b=>b.onclick=manageGuardianLinks);
}
function renderPlayerHub(){
 const root=$("playerHub");if(!root)return;
 const relevantPlayers=players.filter(p=>accounts.some(a=>a.playerId===p.id)||guardianAccounts.some(g=>(g.playerIds||[]).includes(p.id))||guardianRequests.some(r=>r.playerId===p.id&&r.status==="pending")||allRequests.some(r=>r.playerId===p.id));
 root.innerHTML=relevantPlayers.map(p=>{
  const acc=accounts.find(a=>a.approved&&a.playerId===p.id);
  const gs=guardianAccounts.filter(g=>(g.playerIds||[]).includes(p.id));
  const gr=guardianRequests.filter(r=>r.playerId===p.id&&r.status==="pending");
  const open=requests.filter(r=>r.playerId===p.id||(acc&&r.uid===acc.uid));
  const archiveCount=allRequests.filter(r=>(r.playerId===p.id||(acc&&r.uid===acc.uid))&&r.status!=="open").length;
  const pendingPlayerApproval=accounts.some(a=>!a.approved&&!a.rejected&&a.playerId===p.id)?1:0;
  const unansweredPlayerMessages=open.filter(r=>{
    const thread=messages.filter(m=>m.requestId===r.id).sort((a,b)=>ts(a.createdAt)-ts(b.createdAt));
    if(thread.length)return thread[thread.length-1].senderRole!=="coach";
    return true;
  }).length;
  const needs=pendingPlayerApproval+gr.length+unansweredPlayerMessages;
  const guardianHtml=gs.length?gs.map(g=>'<div class="hubGuardianRow"><div><strong>'+esc(g.name||"Foresatt")+'</strong><span>'+esc(g.email||"")+'</span></div><span class="badge '+(g.approved?"ok":"")+'">'+(g.approved?"AKTIV":"VENTER")+'</span><button class="removeGuardianLink danger" data-guardian="'+g.uid+'">Koblinger</button></div>').join(""):'<p class="hubEmpty">Ingen aktive foresatte.</p>';
  const requestHtml=gr.length?gr.map(r=>'<div class="hubPendingGuardian"><div><strong>'+esc(r.guardianName||"Foresatt")+'</strong><span>'+esc(r.guardianEmail||"")+'</span></div><button class="approveGuardianRequest" data-request="'+r.id+'">Godkjenn</button><button class="rejectGuardianRequest danger" data-request="'+r.id+'">Avvis</button></div>').join(""):'<p class="hubEmpty">Ingen foresattforespørsler venter.</p>';
  const conversationHtml=open.length?open.map(r=>'<div class="hubConversation"><div><strong>'+esc(r.title||"Utviklingssamtale")+'</strong><span>'+esc(dateText(r.createdAt))+'</span></div><span class="badge">AKTIV</span></div>').join(""):'<p class="hubEmpty">Ingen aktive samtaler.</p>';
  return '<details class="playerHubCard"><summary><div class="playerHubName"><strong>'+esc(p.navn||p.name||p.id)+'</strong><span>'+(acc?esc(acc.email):"Ingen spillerkonto")+'</span></div><div class="playerHubStats"><span>👨‍👩‍👦 '+gs.length+' foresatt'+(gs.length===1?"":"e")+'</span><span>💬 '+open.length+' aktiv'+(open.length===1?"":"e")+'</span><span>📁 '+archiveCount+'</span></div>'+(needs?'<span class="hubNeeds">'+needs+' krever handling</span>':'<span class="badge ok">OK</span>')+'<span class="guardianChevron">⌄</span></summary><div class="playerHubBody"><section><h4>Spillerkonto</h4>'+(acc?'<div class="hubAccountRow"><div><strong>'+esc(acc.name||p.navn||p.name)+'</strong><span>'+esc(acc.email||"")+'</span></div><span class="badge ok">AKTIV</span><div class="hubAccountActions"><button class="communication" data-communication="'+acc.uid+'">Kommunikasjon</button><button class="archiveOnly" data-archive="'+acc.uid+'">Arkiv ('+archiveCount+')</button><button class="resetApproval danger" data-reset="'+acc.uid+'">Fjern godkjenning (test)</button></div></div>':'<p class="hubEmpty hubWarn">Ingen godkjent spillerkonto er koblet til denne spilleren.</p>')+'</section><section><h4>Foresatte <span>'+gs.length+'</span></h4>'+guardianHtml+'</section>'+(gr.length?'<section class="hubAttention"><h4>Foresattforespørsler <span>'+gr.length+'</span></h4>'+requestHtml+'</section>':'')+'<section><h4>Utvikling og kommunikasjon</h4>'+conversationHtml+(acc?'<div class="hubConversationActions"><button class="communication" data-communication="'+acc.uid+'">Se all kommunikasjon</button><button class="archiveOnly" data-archive="'+acc.uid+'">Åpne arkiv</button></div>':'')+'</section></div></details>';
 }).join("")||'<p class="empty">Ingen aktive spillerbrukere ennå.</p>';
}
async function editConversationTitle(e){const id=e.currentTarget.dataset.title,r=allRequests.find(x=>x.id===id);if(!r)return;const title=prompt("Tittel på samtalen:",r.title||"");if(title===null)return;const clean=title.trim().slice(0,80);try{await updateDoc(doc(db,"developmentRequests",id),{title:clean});await load()}catch(err){console.error("editConversationTitle:",err);alert("Kunne ikke lagre tittelen.")}}
const coachReplyTargets={};
function selectCoachReply(e){const requestId=e.currentTarget.dataset.request,messageId=e.currentTarget.dataset.message,m=messages.find(x=>x.id===messageId),box=$("replytarget-"+requestId);if(!m||!box)return;coachReplyTargets[requestId]=messageId;box.querySelector("p").textContent=m.text||"";box.hidden=false;$("reply-"+requestId)?.focus()}
function clearCoachReply(e){const requestId=e.currentTarget.dataset.request;delete coachReplyTargets[requestId];const box=$("replytarget-"+requestId);if(box)box.hidden=true}
function ts(v){if(!v)return 0;if(typeof v.toDate==="function")return v.toDate().getTime();if(v.seconds)return v.seconds*1000;return 0}
function dateText(v){const n=ts(v);return n?new Date(n).toLocaleString("no-NO",{dateStyle:"medium",timeStyle:"short"}):"Dato ikke tilgjengelig"}
function openArchive(e){const uid=e.currentTarget.dataset.archive,acc=accounts.find(a=>a.uid===uid);if(!acc)return;openCommunication({currentTarget:{dataset:{communication:uid}}});document.querySelectorAll(".archiveConversation").forEach(el=>{if(el.querySelector(".archiveStatus.open"))el.remove()});$("communicationTitle").textContent="Arkiv · "+(acc.name||playerName(acc.playerId));$("communicationSub").textContent="Avsluttede utviklingssamtaler. Du kan åpne en samtale igjen og fortsette dialogen."}
function openCommunication(e){const uid=e.currentTarget.dataset.communication,acc=accounts.find(a=>a.uid===uid);if(!acc)return;const reqs=allRequests.filter(r=>r.uid===uid||r.playerId===acc.playerId).sort((a,b)=>ts(b.createdAt)-ts(a.createdAt));const content=reqs.length?reqs.map(r=>{const thread=messages.filter(m=>m.requestId===r.id).sort((a,b)=>ts(a.createdAt)-ts(b.createdAt));const items='<div class="archiveItem player"><div class="archiveMeta"><strong>'+esc(acc.name||playerName(acc.playerId))+'</strong><span>'+esc(dateText(r.createdAt))+'</span></div><small>STARTET SAMTALEN</small><p>'+esc(r.message||"Ønsker generell tilbakemelding")+'</p></div>'+thread.map(m=>{const parent=m.replyToMessageId?messages.find(x=>x.id===m.replyToMessageId):null;const fallback=!parent&&m.senderRole==="coach"?r:null;return '<div class="archiveItem '+(m.senderRole==="coach"?"coach":"player")+'">'+((parent||fallback)?'<div class="archiveReply"><span>Svar på '+(parent?"melding":"forespørsel")+'</span><p>'+esc(parent?.text||fallback?.message||"Ønsker generell tilbakemelding")+'</p></div>':'')+'<div class="archiveMeta"><strong>'+esc(m.senderRole==="coach"?"Du":(acc.name||playerName(acc.playerId)))+'</strong><span>'+esc(dateText(m.createdAt))+'</span></div><p>'+esc(m.text||"")+'</p></div>'}).join("");return '<section class="archiveConversation"><div class="archiveConversationHead"><div class="archiveTitleBlock"><strong>'+esc(r.title||"Utviklingssamtale")+'</strong><small>'+esc(dateText(r.createdAt))+'</small><span class="archiveStatus '+(r.status==="open"?"open":"closed")+'">'+(r.status==="open"?"AKTIV":"ARKIVERT")+'</span></div><button class="editConversationTitle archiveEditTitle" data-title="'+r.id+'">Rediger tittel</button>'+(r.status==="open"?"":'<button class="reopenConversation" data-reopen="'+r.id+'">Åpne samtalen igjen</button><button class="deleteConversation" data-delete="'+r.id+'">Slett samtale</button>')+'</div><div class="archiveThread">'+items+'</div></section>'}).join(""):'<p class="empty">Ingen kommunikasjon er registrert for denne spilleren.</p>';$("communicationTitle").textContent="Kommunikasjon · "+(acc.name||playerName(acc.playerId));$("communicationSub").textContent="Aktive og arkiverte utviklingssamtaler.";$("communicationBody").innerHTML=content;$("communicationModal").hidden=false;document.body.classList.add("modalOpen");document.querySelectorAll(".reopenConversation").forEach(b=>b.onclick=reopenConversation);document.querySelectorAll(".deleteConversation").forEach(b=>b.onclick=deleteConversation);document.querySelectorAll(".editConversationTitle").forEach(b=>b.onclick=editConversationTitle)}
async function deleteConversation(e){const id=e.currentTarget.dataset.delete,r=allRequests.find(x=>x.id===id);if(!r)return;if(r.status==="open")return alert("Aktive samtaler må markeres som Ferdig før de kan slettes.");const thread=messages.filter(m=>m.requestId===id);const title=r.title||"Utviklingssamtale";if(!confirm('Slette hele samtalen "'+title+'"?\n\nDette sletter forespørselen og '+thread.length+' melding'+(thread.length===1?"":"er")+' permanent. Handlingen kan ikke angres.'))return;const btn=e.currentTarget;btn.disabled=true;btn.textContent="Sletter…";try{const batch=writeBatch(db);thread.forEach(m=>batch.delete(doc(db,"developmentMessages",m.id)));batch.delete(doc(db,"developmentRequests",id));await batch.commit();closeCommunication()}catch(err){console.error("deleteConversation:",err);alert("Kunne ikke slette samtalen. Firestore-regelen for developmentRequests må tillate sletting for coach.");btn.disabled=false;btn.textContent="Slett samtale"}}
async function reopenConversation(e){const id=e.currentTarget.dataset.reopen,r=allRequests.find(x=>x.id===id);if(!r)return;const other=requests.find(x=>x.uid===r.uid&&x.id!==id);if(other)return alert("Spilleren har allerede en aktiv samtale. Avslutt den før du åpner en arkivert samtale.");if(!confirm("Åpne denne samtalen igjen? Spilleren vil kunne svare videre i samme samtale."))return;try{await updateDoc(doc(db,"developmentRequests",id),{status:"open",resolvedAt:null,resolvedBy:null,reopenedAt:serverTimestamp(),reopenedBy:auth.currentUser.uid});closeCommunication();await load()}catch(err){console.error("reopenConversation:",err);alert("Kunne ikke åpne samtalen igjen.")}}
function closeCommunication(){$("communicationModal").hidden=true;document.body.classList.remove("modalOpen")}
$("closeCommunication").onclick=closeCommunication;$("closeCommunicationBottom").onclick=closeCommunication;$("communicationModal").onclick=e=>{if(e.target===$("communicationModal"))closeCommunication()};$("printCommunication").onclick=()=>window.print();
async function rejectAccount(e){const uid=e.currentTarget.dataset.reject,acc=accounts.find(a=>a.uid===uid);if(!acc)return;if(!confirm("Avvise registreringen til "+(acc.name||acc.email)+"?\n\nDette fjerner den ventende spillerregistreringen fra Spillerportal-admin. Selve innloggingskontoen i Firebase Authentication beholdes."))return;try{await updateDoc(doc(db,"playerAccounts",uid),{rejected:true,approved:false,playerId:null,rejectedAt:serverTimestamp(),rejectedBy:auth.currentUser.uid});accounts=accounts.filter(a=>a.uid!==uid);render()}catch(err){console.error("rejectAccount:",err);alert("Kunne ikke avvise registreringen.")}}
async function approve(e){const uid=e.currentTarget.dataset.uid,sel=$("sel-"+uid),playerId=sel.value;if(!playerId)return alert("Velg riktig spiller først.");const acc=accounts.find(a=>a.uid===uid),taken=accounts.find(a=>a.approved&&a.playerId===playerId);if(taken)return alert("Denne spilleren er allerede koblet til "+taken.name+".");if(!confirm("Koble "+acc.name+" ("+acc.email+") til "+playerName(playerId)+"?"))return;await updateDoc(doc(db,"playerAccounts",uid),{approved:true,playerId,approvedAt:serverTimestamp(),approvedBy:auth.currentUser.uid});await load()}
async function resetApproval(e){const uid=e.currentTarget.dataset.reset,acc=accounts.find(a=>a.uid===uid);if(!acc)return;if(!confirm("Fjerne godkjenningen for "+acc.name+"? Kontoen beholdes, men må godkjennes på nytt."))return;await updateDoc(doc(db,"playerAccounts",uid),{approved:false,playerId:null});await load()}
async function sendReply(e){const btn=e.currentTarget,r=requests.find(x=>x.id===btn.dataset.request);if(!r)return;const ta=$("reply-"+r.id),text=ta.value.trim();if(!text)return alert("Skriv en tilbakemelding først.");btn.disabled=true;btn.textContent="Sender…";try{await addDoc(collection(db,"developmentMessages"),{playerId:r.playerId,uid:r.uid,text,senderRole:"coach",createdAt:serverTimestamp(),requestId:r.id,...(coachReplyTargets[r.id]?{replyToMessageId:coachReplyTargets[r.id]}:{})});await load()}catch(err){console.error("sendReply:",err);alert("Kunne ikke sende tilbakemeldingen. Prøv igjen.");btn.disabled=false;btn.textContent="Send svar"}}
async function resolve(e){const id=e.currentTarget.dataset.resolve;if(!confirm("Markere denne forespørselen som ferdig?"))return;await updateDoc(doc(db,"developmentRequests",id),{status:"resolved",resolvedAt:serverTimestamp(),resolvedBy:auth.currentUser.uid});await load()}
onAuthStateChanged(auth,async user=>{try{if(!user)return location.href="index.html";const s=await getDoc(doc(db,"users",user.uid));if(!s.exists()||s.data().role!=="coach")return location.href="index.html";await load();startRealtime()}catch(err){console.error("Auth/admin:",err);$("pendingList").innerHTML="<p class=\"empty\">Feil: "+esc(err.code||err.message)+"</p>"}});